package org.infobip.conversations.common;

public enum ResultCode {
   SUCCESS, ERROR, USERNAME_EXIST, EMAIL_EXIST, PHONE_EXIST, USER_NOT_FOUND, INVALID_PASSWORD, INVALID_TOKEN,
   INVALID_USERNAME, INVALID_STATUS, INVALID_DATA, INVALID_CODE, CODE_EXPIRED, VERIFICATION_SENT, UNAUTHORIZED,
   GROUP_NAME_EXIT, INVALID_ACCESS, PASSWORD_NOT_MATCH,
   TOO_FAST, STILL_NOT_CHECKOUT;


   ResultCode() {
   }
}
